App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 20m
          maxSizeMessage: "Image size over 20M"

App\Request\CreateImageRequest:
  properties:
    image:
      - NotBlank: ~
    entity:
      - NotBlank: ~
    itemID:
      - NotBlank: ~

App\Request\UpdateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\CarCreateRequest:
  properties:
    price:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
    distance:
      - NotBlank: ~
    carType:
      - NotBlank: ~
    city:
      - NotBlank: ~
    country:
      - NotBlank: ~
    gearType:
      - NotBlank: ~

App\Request\CarUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    price:
      - NotBlank: ~
    status:
      - NotBlank: ~
    distance:
      - NotBlank: ~
    carType:
      - NotBlank: ~
    city:
      - NotBlank: ~
    country:
      - NotBlank: ~
    gearType:
      - NotBlank: ~

App\Request\DeviceCreateRequest:
  properties:
    brand:
      - NotBlank: ~
    price:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
    city:
      - NotBlank: ~

App\Request\DeviceUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    brand:
      - NotBlank: ~
    price:
      - NotBlank: ~
    status:
      - NotBlank: ~
    city:
      - NotBlank: ~

App\Request\RealEstateCreateRequest:
  properties:
    city:
      - NotBlank: ~
    space:
      - NotBlank: ~
    price:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\RealEstateUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    city:
      - NotBlank: ~
    space:
      - NotBlank: ~
    price:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\StatusCreateRequest:
  properties:
    createdBy:
      - NotBlank: ~
    lawyerID:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\StatusUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
    lawyerID:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\UserRegisterRequest:
  properties:
    userID:
      - NotBlank: ~
    password:
      - NotBlank: ~

App\Request\UserProfileCreateRequest:
  properties:
    userID:
      - NotBlank: ~
    userName:
      - NotBlank: ~

App\Request\UserProfileUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    userID:
      - NotBlank: ~
    userName:
      - NotBlank: ~

App\Request\FilterRequest:
  properties:
    entity:
      - NotBlank: ~

App\Request\ChatCreateRequest:
  properties:
    itemID:
      - NotBlank: ~
    entity:
      - NotBlank: ~

App\Request\ReportCreateRequest:
  properties:
    itemID:
      - NotBlank: ~
    entity:
      - NotBlank: ~

App\Request\ServiceCreateRequest:
  properties:
    title:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\ServicesUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    title:
      - NotBlank: ~
    type:
      - NotBlank: ~