name: hersay
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Styling
  google_fonts: ^1.1.1

  # Localization Library
  flutter_localizations:
    sdk: flutter

  carousel_slider: ^2.3.1

  # Crypto for SHA1
  crypto: ^2.1.5

  # Dependency injection
  inject:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject

  # Paths
  path_provider: ^1.6.24

  # Shared Prefs
  shared_preferences: ^0.5.12+4

  # Open Url in Chrome
  url_launcher: ^5.7.10

  # Network Agent
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.11

  # String validation
  validators: ^2.0.1

  # Svg Loader
  flutter_svg: ^0.19.1

  # Streams and RX
  rxdart: ^0.25.0

  # ORM, Database SQL
  sqfentity: ^1.4.0+3

  # Firebase Libs
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  firebase_analytics: ^6.3.0
  firebase_remote_config: ^0.4.3
  cloud_firestore: ^0.14.4

  # Google Sign In
  google_sign_in: ^4.5.6
  sign_in_with_apple: ^2.5.4

  # Localization
  gen_lang: ^0.1.3

  # Internationalization
  intl: ^0.16.1
  intl_translation: ^0.17.10
  intl_utils: ^1.9.0

  # Toasts
  fluttertoast: ^7.1.6

  # UUID
  uuid: ^2.2.2

  # Payment
  flutter_credit_card: ^0.1.1

  # Others
  date_time_picker: ^1.1.1
  animate_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1

  test: ^1.15.4

  inject_generator:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject_generator

  # Generate Language Files
  lang_table: 0.2.0

  # Icons Generator
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/300ppi/
    - assets/images/1x/
    - assets/images/SVG/

flutter_intl:
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/300ppi/logo.png"
